apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbetstatic
  namespace: king855-dev
  labels:
    app: qbetstatic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbetstatic
  template:
    metadata:
      labels:
        app: qbetstatic
    spec:
      containers:
        - name: qbetstatic
          image: docker-harbor.clubs999.com/public/nginx:latest
          ports:
          
          - containerPort: 80
          volumeMounts:
            - mountPath: "/usr/share/nginx/html"
              subPath: "king855-dev/html/qbetstatic" 
              name: qbetstatic-data
            - mountPath: "/etc/nginx/conf.d/default.conf"
              subPath: "default.conf"
              name: nginx-vue
          env:
            - name: TZ
              value: "Asia/Shanghai"
            - name: NGINX_PORT
              value: "80"
          resources:
            requests:
              memory: "256Mi"
              cpu: "50m"
            limits:
              memory: "2048Mi"
              cpu: "2000m"
      volumes:
        - name: qbetstatic-data
          persistentVolumeClaim:
            claimName: gluster-claim-pub
        - name: nginx-vue
          configMap:
            name: nginx-vue


apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-vue
  namespace: king855-dev
  labels:
    app: nginx-vue
data:
  default.conf: |
    server {
      listen       80;
      listen  [::]:80;
      server_name  localhost;
    
      access_log  /var/log/nginx/host.access.log  main;
    
      location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
      }
    
      error_page  404              /404.html;
      error_page   500 502 503 504  /50x.html;
      location = /50x.html {
        root   /usr/share/nginx/html;
      }
    }
